services:
    mysql:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: webshop
            MYSQL_USER: webshop
            MYSQL_PASSWORD: webshop
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
            MYSQL_ROOT_HOST: "%"
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
