services:
  webshop-db:
    image: webshop-db:latest
    container_name: webshop-db
    environment:
      MYSQL_DATABASE: webshop
      MYSQL_ROOT_PASSWORD: pasword
      MYSQL_USER: webshop
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  webshop-app:
    image: webshop-app:latest
    container_name: webshop-app
    depends_on:
      - webshop-db
    ports:
      - "3000:80"
    environment:
      DB_HOST: host.docker.internal
      DB_DATABASE: webshop
      DB_USER: webshop
      DB_PASSWORD: password
    volumes:
      - ./app:/var/www/html